name: storage-sync

on:
  push:
    branches:
      - main
      - aws-s3

jobs:
  s3-upload:
    runs-on: 'ubuntu-latest'
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - 
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        audience: sts.amazonaws.com
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

    - 
      name: Sync S3 Bucket
      run: |
        aws s3 cp . s3://visual-asset.polyhedra.network --recursive --exclude ".DS_Store" --exclude ".git/*" --exclude ".github/*" --exclude "*.json" --exclude ".gitignore" --exclude "README.md"